services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: productsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    command:
      - "-path=/migrations"
      - "-database=postgres://user:pass@db:5432/productsdb?sslmode=disable"
      - "up"

volumes:
  db_data:
